CREATE TABLE [dbo].[RefComputers]
(
[ComputerId] [int] NOT NULL IDENTITY(1, 1) NOT FOR REPLICATION,
[Name] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RefComputers] ADD CONSTRAINT [PK_RefComputers] PRIMARY KEY CLUSTERED  ([ComputerId]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RefComputers] ADD CONSTRAINT [IX_RefComputers] UNIQUE NONCLUSTERED  ([Name]) ON [PRIMARY]
GO
